Wrote bubble sort algorithm
MiguelDP4/Bubble-Sort pull request #1
Opened 2020-02-20 19:29 UTC by MiguelDP4

Wrote bubble sort algorithm for both integers and strings.

2020-02-20 22:14 UTC, Forison requested changes
## Status: Require Changes🛑
# 🙋‍♂️ Team,
good job done so far, here are some issues we have to address to get this project approved.
## 👇Check below comments👇
## That is kindly make these changes and submit the project for review
#### Happy coding
#### Addo Forison

2020-02-20 22:14 UTC, Forison commented on bubble.rb
> +def bubble_sort(array)
* [ ] bubble_sort method is implemented and working ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sort.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-1))
 Currently, ```bubble_sort``` is returning nil, hence any example i try also returns nil
```
int_array = [7, 5, 8, 3, 4, 6, 2, 4, 15, 2, 23]
p bubble_sort(int_array) = nil
```
Let us fix this

2020-02-20 22:14 UTC, Forison commented on bubble.rb
> +  end
Return your sorted array here, currently, you are returning nil

2020-02-20 22:14 UTC, Forison commented on bubble.rb
> +  i = 0
* [ ] bubble_sort_by method is implemented and working  ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sortBy.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-1))
currently for this 
```string_array = %w[hi hello hey another_string haloo testing]
p bubble_sort_by(string_array) { |string1, string2| string1.length <=> string2.length }example ```bubble_sort_by``` 
```
returns
``` 
["hi", "hey", "hello", "haloo", "testing", "another_string"]nil
``` 
look closely at the nil at the back of the sorted array. It ought not be there, kindly fix it.

2020-02-20 22:14 UTC, Forison commented on bubble.rb
> +  print array
let us return an array instead of printing array, note method ought to return not print

2020-02-22 06:57 UTC, fatymahmed approved these changes
### Hi @MiguelDP4 @bren2102 
### Great job making all the suggested changes🎉🎉
### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
 _Don't forget to submit your project completion form_

2020-02-22 07:00 UTC, fatymahmed commented on bubble.rb
> +print bubble_sort_by(string_array) { |string1, string2| string1.length - string2.length }
[Optional]
- Please remove this code, you could place it in a different file for the purpose of testing the methods.

2020-02-24 15:33 UTC, merged